name: Events Demo

on:
  issues:
    types: [opened, edited, milestoned]

permissions:
  contents: read

jobs:
  logging:
    name: Logging in the console
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Provide the whole log of this event
        run: |
          echo "----START----"
          echo "this is logging from Events Demo upon ${{ github.event_name }}"
          echo "the action we took is ${{ github.event.action }}"
