name: Events Demo

on:
  schedule:
    - cron: '0 0 * * SUN'

permissions:
  contents: read

jobs:
  create-shell-script:
    name: Create a shell script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: tests
      - run: |
          touch script.sh
          cat >> script.sh << 'EOF'
          #!/bin/bash
          echo "this is a scheduled event executed at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          EOF
          chmod +x script.sh
          ./script.sh

